RD_ROLL_COMMAND_CFG_SH = {}

RD_ROLL_COMMAND_CFG_SH.Radius = 250

RD_ROLL_COMMAND_CFG_SH.Prefix = "Dado"

RD_ROLL_COMMAND_CFG_SH.PrefixColor = Color(162,100,255)

RD_ROLL_COMMAND_CFG_SH.RollColor = Color(52, 198, 235)